name = "TimeseriesMakie"
uuid = "5e3e9a77-7bbf-480c-931c-0802e2453f5a"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"

[extensions]
TimeseriesToolsExt = ["TimeseriesTools"]

[compat]
LinearAlgebra = "1.10"
Makie = "0.24"
Random = "1.10"
TimeseriesTools = "0.7"
julia = "1.10"
